import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_Components/Navbar";
import Footer from "./_Components/Footer";
import { Toaster } from "sonner";
import MySessionProvider from "./_providers/MySessionProvider";
import ShopContext from "./_Context/ShopContext";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.variable} font-sans antialiased min-h-screen flex flex-col`}
      >
        <MySessionProvider>
          <ShopContext>
            <Navbar />
            <main className="mt-27.5 flex-1">{children}</main>
            <Toaster />
            <Footer />
          </ShopContext>
        </MySessionProvider>
      </body>
    </html>
  );
}
