import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_Components/Navbar";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.variable} font-sans antialiased`}
      >
        <Navbar />
        <div className="mt-27.5">{children}</div>
        
      </body>
    </html>
  );
}
